[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Viking docs for aDNA"
authors = [{name = "Surabhi Ranavat", email = "surabhi.ranavat@york.ac.uk"}]
dynamic = ["version", "description"]
